model_name : "RepVGG_Jittor_A0"
model_type: "A"
scale_a: 0.75
scale_b: 2.5
group_conv : 1

data_path : "/root/autodl-tmp/imagenet"
batch_size : 256 
image_size : 224

epochs : 120
lr : 0.1
# warmup_epochs : 5 
weight_decay : 0.0001 
momentum : 0.9
num_workers : 16
min_lr : 0.00001 

chk_point_dir : ./chk_points/jittor_A0
log_dir : ./logs/jittor_A0