model_name : "RepVGG_Torch_B1g2"
model_type: "B"
scale_a: 2
scale_b: 4
group_conv : 2

data_path: "/root/autodl-tmp/imagenet"
batch_size: 128
image_size: 224

epochs: 120
lr: 0.1
weight_decay: 1e-4
momentum: 0.9
num_workers : 16

chk_point_dir : ./chk_points/torch_B1g2
log_dir : ./logs/torch_B1g2