model_name : "RepVGG_Torch_A2_cifar"
model_type: "A"
scale_a: 1.5
scale_b: 2.75
group_conv : 1
num_classes : 100


data_path : "/root/autodl-tmp/cifar100torch"
batch_size : 128 
image_size : 224

epochs : 200 
lr : 0.1
weight_decay : 0.0001 
momentum : 0.9
num_workers : 12
min_lr : 0.00001 

use_amp : false

chk_point_dir : /root/autodl-tmp/chk_points/torch_A2_cifar
log_dir : /root/autodl-tmp/logs/torch_A2_cifar