model_name : "RepVGG_Torch_A0"
model_type: "A"
scale_a: 0.75
scale_b: 2.5
group_conv : 1

data_path : "/root/autodl-tmp/imagenet"
batch_size : 512 
image_size : 224

epochs : 120
lr : 0.1
weight_decay : 0.0001 
momentum : 0.9
num_workers : 16

chk_point_dir : ./chk_points/torch_A0
log_dir : ./logs/torch_A0