model_name : "RepVGG_Torch_B1g2"
model_type: "B"
scale_a: 2
scale_b: 4
group_conv : 2

data_path: "/root/autodl-tmp/imagenet"
batch_size: 512 
image_size: 224

epochs : 120
lr : 0.1
weight_decay : 0.0001 
momentum : 0.9
num_workers : 16
warmup_epochs : 5
min_lr : 0.00001 


chk_point_dir : ./chk_points/torch_B1g2
log_dir : ./logs/torch_B1g2