model_name : "RepVGG_Torch_B1g4"
model_type: "B"
scale_a: 2
scale_b: 4
group_conv : 4 
num_classes : 100


data_path : "/root/autodl-tmp/cifar100torch"

batch_size: 128
image_size: 224

epochs : 200 
lr : 0.1
weight_decay : 0.0001 
momentum : 0.9
num_workers : 16
# warmup_epochs : 5
min_lr : 0.00001 

use_amp : false

chk_point_dir : /root/autodl-tmp/chk_points/torch_B1g2_cifar
log_dir : /root/autodl-tmp/logs/torch_B1g2_cifar