model_name : "RepVGG_Torch_B1_cifar"
model_type: "B"
scale_a: 2 
scale_b: 4 
group_conv : 1
num_classes : 100


data_path : "./cifar100torch"
batch_size : 512 
image_size : 32 

epochs : 250
lr : 0.4
weight_decay : 0.0005
momentum : 0.9
num_workers : 12
min_lr : 0.000001 

use_amp : false

chk_point_dir : ./chk_points/torch_B1_cifar
log_dir : ./logs/torch_B1_cifar