model_name : "resnet_cifar"
# model_type: "A"
# scale_a: 0.75
# scale_b: 2.5
# group_conv : 1
# num_classes : 1000


data_path : "/root/autodl-tmp/cifar100torch"
batch_size : 512 
image_size : 32 

epochs : 250
lr : 0.4
weight_decay : 0.0005 
momentum : 0.9
num_workers : 12
# warmup_epochs : 5
min_lr : 0.00001 

use_amp : false

chk_point_dir : /root/autodl-tmp/chk_points/torch_resnet_cifar
log_dir : /root/autodl-tmp/logs/torch_resnet_cifar