model_name : "RepVGG_Jittor_B1g4"
model_type: "B"
scale_a: 2
scale_b: 4
group_conv : 4 
num_classes : 1000


data_path: "/root/autodl-tmp/imagenet"
batch_size: 192 
image_size: 224

epochs : 5 
lr : 0.1
weight_decay : 0.0001 
momentum : 0.9
num_workers : 16
# warmup_epochs : 5
min_lr : 0.00001 


chk_point_dir : /root/autodl-tmp/chk_points/jittor_B1g2
log_dir : /root/autodl-tmp/logs/jittor_B1g2